import type { Profile } from './profiles'
import { PremiumTier, PremiumFeature, createFreeAccount } from './minglecoin'
import type { MingleCoinAccount } from './minglecoin'
import type { DatingProfile } from './dating'

export interface DemoProfile extends Profile, DatingProfile {
  fitnessStyle: string
  mingleCoins: MingleCoinAccount
  premiumFeatures: PremiumFeature[]
  city: string
}

export const DEMO_PROFILES: DemoProfile[] = [
  {
    id: 'demo_marcus_001',
    name: 'Marcus',
    age: 28,
    bio: 'Competitive Muay Thai fighter and strength coach. I train at dawn, meal prep by noon, and I\'m looking for someone who can keep up — in the gym and beyond. Kink-aware, poly-positive, no judgment zone.',
    avatar_url: null,
    fitnessStyle: 'Martial Arts / Strength',
    city: 'NYC',
    mingleCoins: { ...createFreeAccount(), balance: 320, lifetimeEarned: 870, lifetimeSpent: 550, tier: PremiumTier.STARTER, unlockedFeatures: [PremiumFeature.AdvancedChat, PremiumFeature.VenueInsights] },
    premiumFeatures: [PremiumFeature.AdvancedChat, PremiumFeature.VenueInsights],
    lookingFor: ['training_partner', 'sparring_partner', 'romantic_connection', 'kink_exploration'],
    relationshipStatus: 'single',
    occupation: 'Strength Coach',
    fitnessLevel: 'athlete',
    favoriteActivity: 'Muay Thai',
    indoorOutdoorPref: 'both',
    build: 'muscular',
    sports: ['Muay Thai', 'Strength training', 'Bouldering', 'Swimming'],
  },
  {
    id: 'demo_elena_001',
    name: 'Elena',
    age: 31,
    bio: 'Yoga instructor and wellness curator. I believe movement is medicine and connection is the practice. Switch, kink-friendly, looking for intentional chemistry over small talk.',
    avatar_url: null,
    fitnessStyle: 'Yoga / Pilates / Mobility',
    city: 'NYC',
    mingleCoins: { ...createFreeAccount(), balance: 640, lifetimeEarned: 2100, lifetimeSpent: 1460, tier: PremiumTier.MOMENTUM, unlockedFeatures: [PremiumFeature.AdvancedChat, PremiumFeature.UnlimitedLikes, PremiumFeature.VenueInsights, PremiumFeature.ReadReceipts, PremiumFeature.LifestyleFilters, PremiumFeature.CuratedDateDiscovery, PremiumFeature.VenuePerks] },
    premiumFeatures: [PremiumFeature.AdvancedChat, PremiumFeature.UnlimitedLikes, PremiumFeature.VenueInsights, PremiumFeature.ReadReceipts, PremiumFeature.LifestyleFilters, PremiumFeature.CuratedDateDiscovery, PremiumFeature.VenuePerks],
    lookingFor: ['romantic_connection', 'lifestyle_partner', 'kink_exploration'],
    relationshipStatus: 'polyamorous',
    occupation: 'Yoga Instructor',
    fitnessLevel: 'advanced',
    favoriteActivity: 'Vinyasa Flow',
    indoorOutdoorPref: 'indoor',
    build: 'athletic',
    sports: ['Yoga', 'Pilates', 'Meditation', 'Hiking'],
    kinkDatePreferences: ['Rope bondage', 'Sensory play', 'Sound baths'],
  },
  {
    id: 'demo_david_001',
    name: 'David',
    age: 26,
    bio: 'Division I swimmer turned open-water enthusiast. New to the kink scene but eager to explore with the right guide. Fitness is my therapy, vulnerability is my edge.',
    avatar_url: null,
    fitnessStyle: 'Swimming / Cardio / Functional',
    city: 'Boston',
    mingleCoins: { ...createFreeAccount(), balance: 150, lifetimeEarned: 420, lifetimeSpent: 270, tier: PremiumTier.FREE, unlockedFeatures: [] },
    premiumFeatures: [],
    lookingFor: ['training_partner', 'romantic_connection', 'kink_exploration'],
    relationshipStatus: 'single',
    occupation: 'Software Engineer',
    fitnessLevel: 'intermediate',
    favoriteActivity: 'Open water swimming',
    indoorOutdoorPref: 'outdoor',
    build: 'athletic',
    sports: ['Swimming', 'Running', 'Cycling'],
  },
  {
    id: 'demo_sarah_001',
    name: 'Sarah',
    age: 29,
    bio: 'CrossFit competitor by morning, lifestyle dominatrix by night. I lead in the box and in the bedroom. If you can handle burpees and obedience, we might have something.',
    avatar_url: null,
    fitnessStyle: 'CrossFit / HIIT / Powerlifting',
    city: 'LA',
    mingleCoins: { ...createFreeAccount(), balance: 1280, lifetimeEarned: 4500, lifetimeSpent: 3220, tier: PremiumTier.PEAK, unlockedFeatures: [PremiumFeature.AdvancedChat, PremiumFeature.UnlimitedLikes, PremiumFeature.VenueInsights, PremiumFeature.ReadReceipts, PremiumFeature.PriorityMatching, PremiumFeature.IncognitoMode, PremiumFeature.VerifiedBadge, PremiumFeature.LifestyleFilters, PremiumFeature.KinkDiscovery, PremiumFeature.CuratedDateDiscovery, PremiumFeature.VenuePerks] },
    premiumFeatures: [PremiumFeature.AdvancedChat, PremiumFeature.UnlimitedLikes, PremiumFeature.VenueInsights, PremiumFeature.ReadReceipts, PremiumFeature.PriorityMatching, PremiumFeature.IncognitoMode, PremiumFeature.VerifiedBadge, PremiumFeature.LifestyleFilters, PremiumFeature.KinkDiscovery, PremiumFeature.CuratedDateDiscovery, PremiumFeature.VenuePerks],
    lookingFor: ['lifestyle_partner', 'accountability_partner', 'kink_exploration'],
    relationshipStatus: 'open_relationship',
    occupation: 'Personal Trainer',
    fitnessLevel: 'athlete',
    favoriteActivity: 'CrossFit',
    indoorOutdoorPref: 'indoor',
    build: 'muscular',
    sports: ['CrossFit', 'Powerlifting', 'Weightlifting'],
    kinkDatePreferences: ['Impact play', 'Leather craft', 'Dungeon nights'],
  },
  {
    id: 'demo_james_001',
    name: 'James',
    age: 34,
    bio: 'Marathon runner and weekend brunch enthusiast. Looking for a training partner who also enjoys a good mimosa. Chill vibes only.',
    avatar_url: null,
    fitnessStyle: 'Running / Cardio',
    city: 'Chicago',
    mingleCoins: { ...createFreeAccount(), balance: 510, lifetimeEarned: 1200, lifetimeSpent: 690, tier: PremiumTier.STARTER, unlockedFeatures: [PremiumFeature.AdvancedChat, PremiumFeature.VenueInsights] },
    premiumFeatures: [PremiumFeature.AdvancedChat, PremiumFeature.VenueInsights],
    lookingFor: ['training_partner', 'friendship', 'casual_dating'],
    relationshipStatus: 'single',
    occupation: 'Architect',
    fitnessLevel: 'advanced',
    favoriteActivity: 'Long distance running',
    indoorOutdoorPref: 'outdoor',
    build: 'slender',
    sports: ['Running', 'Cycling', 'Yoga'],
  },
  {
    id: 'demo_priya_001',
    name: 'Priya',
    age: 27,
    bio: 'Hot yoga devotee and plant-based chef. I believe in healing through movement and whole foods. Looking for someone to share sun salutations and Sunday brunch.',
    avatar_url: null,
    fitnessStyle: 'Yoga / Pilates / Mobility',
    city: 'Miami',
    mingleCoins: { ...createFreeAccount(), balance: 890, lifetimeEarned: 2100, lifetimeSpent: 1210, tier: PremiumTier.MOMENTUM, unlockedFeatures: [PremiumFeature.AdvancedChat, PremiumFeature.UnlimitedLikes, PremiumFeature.VenueInsights, PremiumFeature.ReadReceipts, PremiumFeature.LifestyleFilters, PremiumFeature.CuratedDateDiscovery, PremiumFeature.VenuePerks] },
    premiumFeatures: [PremiumFeature.AdvancedChat, PremiumFeature.UnlimitedLikes, PremiumFeature.VenueInsights, PremiumFeature.ReadReceipts, PremiumFeature.LifestyleFilters, PremiumFeature.CuratedDateDiscovery, PremiumFeature.VenuePerks],
    lookingFor: ['romantic_connection', 'friendship', 'accountability_partner'],
    relationshipStatus: 'single',
    occupation: 'Chef',
    fitnessLevel: 'intermediate',
    favoriteActivity: 'Hot yoga',
    indoorOutdoorPref: 'indoor',
    build: 'slender',
    sports: ['Yoga', 'Pilates', 'Swimming'],
  },
  {
    id: 'demo_tyler_001',
    name: 'Tyler',
    age: 30,
    bio: 'Ex-D1 wrestler turned BJJ black belt. Coach by trade, competitor at heart. Looking for a partner who understands discipline and isn\'t afraid to get gritty.',
    avatar_url: null,
    fitnessStyle: 'Martial Arts / Strength',
    city: 'Detroit',
    mingleCoins: { ...createFreeAccount(), balance: 2200, lifetimeEarned: 6800, lifetimeSpent: 4600, tier: PremiumTier.PEAK, unlockedFeatures: [PremiumFeature.AdvancedChat, PremiumFeature.UnlimitedLikes, PremiumFeature.VenueInsights, PremiumFeature.ReadReceipts, PremiumFeature.PriorityMatching, PremiumFeature.IncognitoMode, PremiumFeature.VerifiedBadge, PremiumFeature.LifestyleFilters, PremiumFeature.KinkDiscovery, PremiumFeature.CuratedDateDiscovery, PremiumFeature.VenuePerks] },
    premiumFeatures: [PremiumFeature.AdvancedChat, PremiumFeature.UnlimitedLikes, PremiumFeature.VenueInsights, PremiumFeature.ReadReceipts, PremiumFeature.PriorityMatching, PremiumFeature.IncognitoMode, PremiumFeature.VerifiedBadge, PremiumFeature.LifestyleFilters, PremiumFeature.KinkDiscovery, PremiumFeature.CuratedDateDiscovery, PremiumFeature.VenuePerks],
    lookingFor: ['training_partner', 'sparring_partner', 'romantic_connection'],
    relationshipStatus: 'single',
    occupation: 'BJJ Coach',
    fitnessLevel: 'athlete',
    favoriteActivity: 'Brazilian Jiu-Jitsu',
    indoorOutdoorPref: 'indoor',
    build: 'muscular',
    sports: ['BJJ', 'Wrestling', 'Strength training', 'Boxing'],
  },
]
